[package]
name = "rust-gendex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
fancy-regex = "0.10.0"
regex = "1"
glob = "0.3.0"
walkdir = "2.3.2"
handlebars = "^4.3.3"
serde_json = "^1.0.83"
